title: boris andrews
show_downloads: false
google_analytics: G-CP6X0DRVGM
email: boris.andrews@maths.ox.ac.uk
description: dphil (phd) student, university of oxford

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
